# Generated by Django 2.0 on 2018-01-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_account',
            name='name',
        ),
    ]
